emw/emw/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# default: "Django Administration"
admin.site.site_header = 'EMW Admin'
# default: "Site administration"
# admin.site.index_title = 'Features area'
# default: "Django site admin"
# admin.site.site_title = 'HTML title from adminsitration'

urlpatterns = [
    path('emw/admin/', admin.site.urls),
    path('', include('corporate.urls')),
    path('faqs/', include('faqs.urls')),
    path('', include('news_blog.urls')),
    path('', include('portifolio_clients.urls')),
    path('queries/', include('queries.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

emw/news_blog/urls.py
from django.urls import path
from .views import (
    news_blog_detail,
    search_blog_news,
    new_articles
)


app_name = 'news_blog'
urlpatterns = [
    path('media/<slug:slug>', news_blog_detail, name='news_blog_detail'),
    path('<str:type>', new_articles, name='new_articles'),
    path('search', search_blog_news, name='search_blog_news'),

]

emw/news_blog/models.py
from django.db import models
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.


class BlogNews(models.Model):
    OPTION = (
        ('', 'Select Category'),
        ('news', 'News'),
        ('articles', 'Articles'),

    )
    category = models.CharField(max_length=50, choices=OPTION)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='Admin')
    image = models.ImageField(upload_to='blog/%Y/%m/')
    description = RichTextUploadingField()
    tag = models.ManyToManyField('Tag')
    slug = models.SlugField(unique=True)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-timestamp']
        verbose_name_plural = 'News or Article'

    # def get_absolute_url(self):
    #     return reverse('blog:articles-details',kwargs={'slug':self.slug})


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-timestamp']

emw/news_blog/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.core.paginator import Paginator
from .models import BlogNews

# Create your views here.


def news_blog_detail(request, slug):
    template_name = 'news_blog/news_blog_detail.html'
    bn = BlogNews.objects.all()
    news = bn.filter(category='news').count()
    articles = bn.filter(category='articles').count()
    qs = get_object_or_404(BlogNews, slug=slug)
    return render(request, template_name, {'obj': qs, 'news': news, 'articles': articles})


def new_articles(request, type):
    template_name = 'news_blog/news_blog.html'
    qs_all = BlogNews.objects.all()
    if type != 'all':
        news_articles_list = qs_all.filter(category=type)
        paginator = Paginator(news_articles_list, 3)
        page = request.GET.get('page')
        qs = paginator.get_page(page)
        return render(request, template_name, {'obj': qs, 'type': type})
    paginator = Paginator(qs_all, 3)
    page = request.GET.get('page')
    qs = paginator.get_page(page)
    return render(request, template_name, {'obj': qs, 'type': 'NEWS & ARTICLES'})


def search_blog_news(request):
    template_name = 'news_blog/search.html'
    if request.method == 'GET':
        query = request.GET.get('q')
        if query is not None:
            lookups = Q(title__icontains=query) | Q(
                description__icontains=query) | Q(category__icontains=query)
            results_list = BlogNews.objects.filter(lookups).distinct()
            paginator = Paginator(results_list, 3)
            page = request.GET.get('page')
            results = paginator.get_page(page)
            context = {'obj': results, 'query': query}
            return render(request, template_name, context)
        else:
            return render(request, template_name)
    else:
        return render(request, template_name)

emw/templates/news_blog/news_blog.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}EMW | {{type|title}} {% endblock %}
{% block content %}
<div class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="page-section">
                    <h1 class="page-title ">{{type|title}} </h1>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="space-medium">
    <div class="container">
        <div class="row">
            {% if obj %}
            {% for a in obj %}
            {% include 'base/snippets/news_blog.html' with instance=a %}
            {% endfor %}
            {% else %}
            <div class="col-md-6 col-md-offset-3 text-center">
                <h1>No Posts yet </h1>
            </div>
            {% endif %}
        </div>
        {% if obj %}
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <!-- pagination start -->
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="st-pagination">
                        <ul class="pagination">
                            {% if obj.has_previous %}
                            <li><a href="?page=1" aria-label="previous"><span aria-hidden="true">&laquo;
                                        first</span></a> </li>
                            <li><a href="?page={{ obj.previous_page_number }}" aria-label="previous"><span
                                        aria-hidden="true">Previous</span></a> </li>
                            {% endif %}
                            <li><a href="#"> Page {{ obj.number }} of {{ obj.paginator.num_pages }}</a></li>
                            {% if obj.has_next %}
                            <li> <a href="?page={{ obj.next_page_number }}" aria-label="Next"><span
                                        aria-hidden="true">Next</span></a> </li>
                            <li> <a href="?page={{ obj.paginator.num_pages }}" aria-label="Next"><span
                                        aria-hidden="true">Last &raquo;</span></a> </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <!-- pagination close -->
            </div>
        </div>
        {% endif %}

    </div>
</div>
{% endblock %}

emw/templates/news_blog/news_blog_detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}EMW | {{obj.title}} {% endblock %}
{% block content %}
<div class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="page-section">
                    <!-- <h1 class="page-title ">{{obj.title}} </h1> -->
                    <!-- <p class="page-text">{{obj.project_name}} </p> -->
                </div>
            </div>
        </div>
    </div>
</div>
<div class="space-medium">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                <div class="row">
                    <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
                        <!-- post holder -->
                        <div class="post-header">
                            <!-- post header -->
                            <h1 class="post-title text-center"><a href="#" class="title">{{obj.title}}</h1>
                            <div class="meta"> <span class="meta-date">{{obj.timestamp|date:"M d Y"}}</span> / <span
                                    class="meta-categories">in<a href="#">{{obj.category|title}}</a></span> / <span
                                    class="meta-author">By <a href="#">{{obj.author|title}}</a></span>
                            </div>
                        </div>
                        <div class="post-content">
                            {{obj.description|safe}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <!-- widget-search-start -->
                <div class=" widget-search">

                    <form method="GET" action="{% url 'news_blog:search_blog_news' %}">
                        {% csrf_token %}
                        <div class="search-form">
                            <input type="text" class="form-control" placeholder="Search Here" name="q">
                            <button type="Submit"><i class="fa fa-search"></i></button>
                        </div>
                    </form>
                </div>
                <!-- widget-search-close -->
                <!-- widget-categories-start -->
                <div class=" widget widget-categories">
                    <h2 class="widget-title">Categories</h2>
                    <ul class="angle angle-right">
                        <li class="active"> <a href="{% url 'news_blog:new_articles' 'news' %}">News ({{news}})</a></li>
                        <li> <a href="{% url 'news_blog:new_articles' 'articles' %}">Articles ({{articles}})</a></li>

                    </ul>
                </div>


                <div class=" widget widget-tags ">
                    <h2 class=" widget-title">Tags</h2>
                    {% if obj.tag %}
                    {% for t in obj.tag.all %}
                    <a href="#">{{t.name}}</a>
                    {% endfor %}
                    {% endif %}
                </div>
                <!-- widget-Tag close -->
            </div>
        </div>
    </div>
</div>
{% endblock %}

emw/templates/news_blog/search.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}EMW | Search Results {% endblock %}
{% block content %}
<div class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="page-section">
                    <h1 class="page-title ">Search Results for: {{query}} </h1>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="space-medium">
    <div class="container">
        <div class="row">
            {% if obj %}
            {% for s in obj %}
            {% include 'base/snippets/news_blog.html' with instance=s %}
            {% endfor %}
            {% else %}
            <div class="col-md-6 col-md-offset-3 text-center">
                <h1>No Search Results Found for {{query}} </h1>
            </div>
            {% endif %}
        </div>
        {% if obj %}
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <!-- pagination start -->
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="st-pagination">
                        <ul class="pagination">
                            {% if obj.has_previous %}
                            <li><a href="?page=1" aria-label="previous"><span aria-hidden="true">&laquo;
                                        first</span></a> </li>
                            <li><a href="?page={{ obj.previous_page_number }}" aria-label="previous"><span
                                        aria-hidden="true">Previous</span></a> </li>
                            {% endif %}
                            <li><a href="#"> Page {{ obj.number }} of {{ obj.paginator.num_pages }}</a></li>
                            {% if obj.has_next %}
                            <li> <a href="?page={{ obj.next_page_number }}" aria-label="Next"><span
                                        aria-hidden="true">Next</span></a> </li>
                            <li> <a href="?page={{ obj.paginator.num_pages }}" aria-label="Next"><span
                                        aria-hidden="true">Last &raquo;</span></a> </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <!-- pagination close -->
            </div>
        </div>
        {% endif %}

    </div>
</div>
{% endblock %}