emw/corporate/urls.py
from django.urls import path
from .views import (
    home,
    contact,
    contracting,
    logistics,
    construction_and_civils,
    joinery,
    steel_fabrication,
    general_trucks,
    specialised_trucks,
)

app_name = 'corporate'
urlpatterns = [
    path('', home, name='home'),
    path('contact-us', contact, name='contact'),
    path('contracting', contracting, name='contracting'),
    path('logistics', logistics, name='logistics'),
    path('contracting/construction-and-civils',
         construction_and_civils, name='construction_and_civils'),
    path('contracting/joinery', joinery, name='joinery'),
    path('contracting/steel-fabrication',
         steel_fabrication, name='steel_fabrication'),
    path('logistics/general-trucks', general_trucks, name='general_trucks'),
    path('logistics/specialised-trucks',
         specialised_trucks, name='specialised_trucks'),

]

emw/emw/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# default: "Django Administration"
admin.site.site_header = 'EMW Admin'
# default: "Site administration"
# admin.site.index_title = 'Features area'
# default: "Django site admin"
# admin.site.site_title = 'HTML title from adminsitration'

urlpatterns = [
    path('emw/admin/', admin.site.urls),
    path('', include('corporate.urls')),
    path('faqs/', include('faqs.urls')),
    path('', include('news_blog.urls')),
    path('', include('portifolio_clients.urls')),
    path('queries/', include('queries.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

emw/corporate/models.py
from django.db import models

# Create your models here.


class Slider(models.Model):
    background_image = models.ImageField(
        upload_to='bg/')
    title = models.CharField(max_length=255)
    sub_title = models.CharField(max_length=255)
    button_title = models.CharField(max_length=255)
    button_link = models.URLField(max_length=255)
    updated = models.DateTimeField(auto_now=True)
    position = models.PositiveIntegerField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["position", ]

emw/corporate/views.py
from django.shortcuts import render, redirect
from django.core.mail import EmailMessage
from django.contrib import messages
from .models import (
    Slider
)
from portifolio_clients.models import (
    Client, Project
)
from news_blog.models import BlogNews
from .utils import send_email

# Create your views here.


def home(request):
    template_name = 'corporate/home.html'
    sliders_qs = Slider.objects.all()
    blog_news_qs = BlogNews.objects.all()[:1]
    project_qs = Project.objects.all()[:3]
    context = {
        'sliders': sliders_qs,
        'blog_news': blog_news_qs,
        'projects': project_qs
    }
    return render(request, template_name, context)


def contact(request):
    template_name = 'corporate/contact.html'
    if request.method == 'POST':
        name = request.POST.get('name')
        subject = request.POST.get('subject')
        email = request.POST.get('email')
        textarea = request.POST.get('textarea')
        send_email(request, name, email, subject, textarea)
    return render(request, template_name)


def logistics(request):
    template_name = 'corporate/services/logistics_overview.html'
    return render(request, template_name)


def contracting(request):
    template_name = 'corporate/services/contracting_overview.html'
    return render(request, template_name)

# contracting services


def construction_and_civils(request):
    template_name = 'corporate/services/contracting_civil.html'
    return render(request, template_name)


def joinery(request):
    template_name = 'corporate/services/contracting_joinery.html'
    return render(request, template_name)


def steel_fabrication(request):
    template_name = 'corporate/services/contracting_steel_fabrication.html'
    return render(request, template_name)

# logistics servies


def general_trucks(request):
    template_name = 'corporate/services/logistics_general_trucks.html'
    return render(request, template_name)


def specialised_trucks(request):
    template_name = 'corporate/services/logistics_specialised_trucks.html'
    return render(request, template_name)

emw/templates/corporate/services/contracting_civil.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}EMW | Construction & Civils {% endblock %}
{% block content %}
<div class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="page-section">
                    <h1 class="page-title ">Construction & Civil </h1>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="pdt80">
    <div class="container">
        <div class="author-block">
            <!-- Post author -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="author-img">
                        <a href="#"><img src="{% static 'images/author.jpg' %}" class="img-circle" alt="Brick work"></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <div class="author-post-content ">
                        <div class="author-header">
                            <h3><a href="#" class="title">Brick work</a></h3>
                        </div>
                        <div class="author-content">
                            <p>Etiam laoreet sitamet purus sed vestibulu ullam cursus lacus eget pharetra accumsan ante
                                metus tinante in ones leousce in consectetur lacus non efficiturex.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="author-block">
            <!-- Post author -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="author-img">
                        <a href="#"><img src="{% static 'images/author.jpg' %}" class="img-circle"
                                alt="Concrete works"></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <div class="author-post-content ">
                        <div class="author-header">
                            <h3><a href="#" class="title">Concrete works</a></h3>
                        </div>
                        <div class="author-content">
                            <p>Etiam laoreet sitamet purus sed vestibulu ullam cursus lacus eget pharetra accumsan ante
                                metus tinante in ones leousce in consectetur lacus non efficiturex.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="author-block">
            <!-- Post author -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="author-img">
                        <a href="#"><img src="{% static 'images/author.jpg' %}" class="img-circle" alt="plastering"></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <div class="author-post-content ">
                        <div class="author-header">
                            <h3><a href="#" class="title">Plastering</a></h3>
                        </div>
                        <div class="author-content">
                            <p>Etiam laoreet sitamet purus sed vestibulu ullam cursus lacus eget pharetra accumsan ante
                                metus tinante in ones leousce in consectetur lacus non efficiturex.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="author-block">
            <!-- Post author -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="author-img">
                        <a href="#"><img src="{% static 'images/author.jpg' %}" class="img-circle" alt="paving"></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <div class="author-post-content ">
                        <div class="author-header">
                            <h3><a href="#" class="title">Paving</a></h3>
                        </div>
                        <div class="author-content">
                            <p>Etiam laoreet sitamet purus sed vestibulu ullam cursus lacus eget pharetra accumsan ante
                                metus tinante in ones leousce in consectetur lacus non efficiturex.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="author-block">
            <!-- Post author -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="author-img">
                        <a href="#"><img src="{% static 'images/author.jpg' %}" class="img-circle"
                                alt="excavations"></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <div class="author-post-content ">
                        <div class="author-header">
                            <h3><a href="#" class="title">Excavations</a></h3>
                        </div>
                        <div class="author-content">
                            <p>Etiam laoreet sitamet purus sed vestibulu ullam cursus lacus eget pharetra accumsan ante
                                metus tinante in ones leousce in consectetur lacus non efficiturex.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="author-block">
            <!-- Post author -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="author-img">
                        <a href="#"><img src="{% static 'images/author.jpg' %}" class="img-circle" alt="trenching"></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <div class="author-post-content ">
                        <div class="author-header">
                            <h3><a href="#" class="title">Trenching</a></h3>
                        </div>
                        <div class="author-content">
                            <p>Etiam laoreet sitamet purus sed vestibulu ullam cursus lacus eget pharetra accumsan ante
                                metus tinante in ones leousce in consectetur lacus non efficiturex.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

emw/templates/corporate/services/contracting_joinery.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}EMW | Joinery {% endblock %}
{% block content %}
<div class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="page-section">
                    <h1 class="page-title ">Joinery </h1>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="pdt80">
    <div class="container">
        <div class="author-block">
            <!-- Post author -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="author-img">
                        <a href="#"><img src="{% static 'images/author.jpg' %}" class="img-circle"
                                alt="Work stations"></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <div class="author-post-content ">
                        <div class="author-header">
                            <h3><a href="#" class="title">Work Stations</a>
                            </h3>
                        </div>
                        <div class="author-content">
                            <p>Etiam laoreet sitamet purus sed vestibulu ullam cursus lacus eget pharetra accumsan ante
                                metus tinante in ones leousce in consectetur lacus non efficiturex.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="author-block">
            <!-- Post author -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="author-img">
                        <a href="#"><img src="{% static 'images/author.jpg' %}" class="img-circle" alt="cabinets"></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <div class="author-post-content ">
                        <div class="author-header">
                            <h3><a href="#" class="title">cabinets</a>
                            </h3>
                        </div>
                        <div class="author-content">
                            <p>Etiam laoreet sitamet purus sed vestibulu ullam cursus lacus eget pharetra accumsan ante
                                metus tinante in ones leousce in consectetur lacus non efficiturex.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="author-block">
            <!-- Post author -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="author-img">
                        <a href="#"><img src="{% static 'images/author.jpg' %}" class="img-circle"
                                alt="custom joinery"></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <div class="author-post-content ">
                        <div class="author-header">
                            <h3><a href="#" class="title">custom joinery</a>
                            </h3>
                        </div>
                        <div class="author-content">
                            <p>Etiam laoreet sitamet purus sed vestibulu ullam cursus lacus eget pharetra accumsan ante
                                metus tinante in ones leousce in consectetur lacus non efficiturex.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

emw/templates/corporate/services/contracting_overview.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}EMW | Contracting Services{% endblock %}
{% block content %}
<div class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="page-section">
                    <h1 class="page-title ">Contracting Services </h1>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="space-medium">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
                <div class="related-post">
                    <!-- related post -->
                    <div class="related-img">
                        <a href="{% url 'corporate:steel_fabrication' %}" class="imghover"><img
                                src="{% static 'images/related-post-2.jpg' %}" alt="steel-fabrication"
                                class="img-responsive" style="width: 100%;"></a>
                    </div>
                    <div class="related-post-content">
                        <h4 class="related-title"><a href="{% url 'corporate:steel_fabrication' %}" class="title">Steel
                                Fabrication</a></h4>

                    </div>
                </div>
                <!-- /.related post -->
            </div>
            <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
                <div class="related-post">
                    <!-- related post -->
                    <div class="related-img">
                        <a href="{% url 'corporate:joinery' %}" class="imghover"><img
                                src="{% static 'images/related-post-1.jpg' %}" alt="joinery" class="img-responsive"
                                style="width: 100%;"></a>
                    </div>
                    <div class="related-post-content">
                        <h4 class="related-title"><a href="{% url 'corporate:joinery' %}" class="title">Joinery
                            </a></h4>

                    </div>
                </div>
                <!-- /.related post -->
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
                <div class="related-post">
                    <!-- related post -->
                    <div class="related-img">
                        <a href="{% url 'corporate:construction_and_civils' %}" class="imghover"><img
                                src="{% static 'images/related-post-2.jpg' %}" alt="construction-and-civil"
                                class="img-responsive" style="width: 100%;"></a>
                    </div>
                    <div class="related-post-content">
                        <h4 class="related-title"><a href="{% url 'corporate:construction_and_civils' %}"
                                class="title">Contraction
                                &amp;
                                Civils</a></h4>

                    </div>
                </div>
                <!-- /.related post -->
            </div>
        </div>
    </div>
</div>
{% endblock %}

emw/templates/corporate/services/contracting_steel_fabrication.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}EMW | Steel Fabrication {% endblock %}
{% block content %}
<div class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="page-section">
                    <h1 class="page-title ">Steel Fabrication </h1>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="pdt80">
    <div class="container">
        <div class="author-block">
            <!-- Post author -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="author-img">
                        <a href="#"><img src="{% static 'images/author.jpg' %}" class="img-circle"
                                alt="conversion of shipping containers into offices or homes"></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <div class="author-post-content ">
                        <div class="author-header">
                            <h3><a href="#" class="title">Conversion of shipping containers into offices or homes</a>
                            </h3>
                        </div>
                        <div class="author-content">
                            <p>Etiam laoreet sitamet purus sed vestibulu ullam cursus lacus eget pharetra accumsan ante
                                metus tinante in ones leousce in consectetur lacus non efficiturex.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="author-block">
            <!-- Post author -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="author-img">
                        <a href="#"><img src="{% static 'images/author.jpg' %}" class="img-circle"
                                alt="Steel Sheds"></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <div class="author-post-content ">
                        <div class="author-header">
                            <h3><a href="#" class="title">Steel Sheds</a>
                            </h3>
                        </div>
                        <div class="author-content">
                            <p>Etiam laoreet sitamet purus sed vestibulu ullam cursus lacus eget pharetra accumsan ante
                                metus tinante in ones leousce in consectetur lacus non efficiturex.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="author-block">
            <!-- Post author -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="author-img">
                        <a href="#"><img src="{% static 'images/author.jpg' %}" class="img-circle"
                                alt="general welding"></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <div class="author-post-content ">
                        <div class="author-header">
                            <h3><a href="#" class="title">General Welding</a>
                            </h3>
                        </div>
                        <div class="author-content">
                            <p>Etiam laoreet sitamet purus sed vestibulu ullam cursus lacus eget pharetra accumsan ante
                                metus tinante in ones leousce in consectetur lacus non efficiturex.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

emw/templates/corporate/services/logistics_general_trucks.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}EMW | General Trucks {% endblock %}
{% block content %}
<div class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="page-section">
                    <h1 class="page-title ">General Trucks </h1>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="pdt80">
    <div class="container">
        <div class="author-block">
            <!-- Post author -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="author-img">
                        <a href="#"><img src="{% static 'images/author.jpg' %}" class="img-circle"
                                alt="Flatbed trucks"></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <div class="author-post-content ">
                        <div class="author-header">
                            <h3><a href="#" class="title">Flatbed Trucks</a>
                            </h3>
                        </div>
                        <div class="author-content">
                            <p>Etiam laoreet sitamet purus sed vestibulu ullam cursus lacus eget pharetra accumsan ante
                                metus tinante in ones leousce in consectetur lacus non efficiturex.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="author-block">
            <!-- Post author -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="author-img">
                        <a href="#"><img src="{% static 'images/author.jpg' %}" class="img-circle"
                                alt="Dropside trucks"></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <div class="author-post-content ">
                        <div class="author-header">
                            <h3><a href="#" class="title">Dropside Trucks</a>
                            </h3>
                        </div>
                        <div class="author-content">
                            <p>Etiam laoreet sitamet purus sed vestibulu ullam cursus lacus eget pharetra accumsan ante
                                metus tinante in ones leousce in consectetur lacus non efficiturex.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="author-block">
            <!-- Post author -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="author-img">
                        <a href="#"><img src="{% static 'images/author.jpg' %}" class="img-circle"
                                alt="Boxed trucks"></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <div class="author-post-content ">
                        <div class="author-header">
                            <h3><a href="#" class="title">Boxed Trucks</a>
                            </h3>
                        </div>
                        <div class="author-content">
                            <p>Etiam laoreet sitamet purus sed vestibulu ullam cursus lacus eget pharetra accumsan ante
                                metus tinante in ones leousce in consectetur lacus non efficiturex.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

emw/templates/corporate/services/logistics_overview.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}EMW | Logistics Services{% endblock %}
{% block content %}
<div class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="page-section">
                    <h1 class="page-title ">Logistics Services </h1>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="space-medium">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
                <div class="related-post">
                    <!-- related post -->
                    <div class="related-img">
                        <a href="{% url 'corporate:specialised_trucks' %}" class="imghover"><img
                                src="{% static 'images/related-post-2.jpg' %}" alt="specialised-trucks"
                                class="img-responsive" style="width: 100%;"></a>
                    </div>
                    <div class="related-post-content">
                        <h4 class="related-title"><a href="{% url 'corporate:specialised_trucks' %}"
                                class="title">Specialised Trucks</a></h4>

                    </div>
                </div>
                <!-- /.related post -->
            </div>
            <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
                <div class="related-post">
                    <!-- related post -->
                    <div class="related-img">
                        <a href="{% url 'corporate:general_trucks' %}" class="imghover"><img
                                src="{% static 'images/related-post-1.jpg' %}" alt="general-trucks"
                                class="img-responsive" style="width: 100%;"></a>
                    </div>
                    <div class="related-post-content">
                        <h4 class="related-title"><a href="{% url 'corporate:general_trucks' %}" class="title">General
                                Trucks
                            </a></h4>

                    </div>
                </div>
                <!-- /.related post -->
            </div>
        </div>
    </div>
</div>
{% endblock %}