emw/emw/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# default: "Django Administration"
admin.site.site_header = 'EMW Admin'
# default: "Site administration"
# admin.site.index_title = 'Features area'
# default: "Django site admin"
# admin.site.site_title = 'HTML title from adminsitration'

urlpatterns = [
    path('emw/admin/', admin.site.urls),
    path('', include('corporate.urls')),
    path('faqs/', include('faqs.urls')),
    path('', include('news_blog.urls')),
    path('', include('portifolio_clients.urls')),
    path('queries/', include('queries.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

emw/news_blog/urls.py
from django.urls import path
from .views import (
    news_blog_detail,
    search_blog_news,
    new_articles
)


app_name = 'news_blog'
urlpatterns = [
    path('media/<slug:slug>', news_blog_detail, name='news_blog_detail'),
    path('<str:type>', new_articles, name='new_articles'),
    path('search', search_blog_news, name='search_blog_news'),

]

emw/portifolio_clients/urls.py
from django.urls import path
from .views import (
    project_details,
    projects
)


app_name = 'portifolio_clients'
urlpatterns = [
    path('project/<slug:slug>', project_details, name='project_details'),
    path('projects/all', projects, name='projects')

]

emw/news_blog/models.py
from django.db import models
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.


class BlogNews(models.Model):
    OPTION = (
        ('', 'Select Category'),
        ('news', 'News'),
        ('articles', 'Articles'),

    )
    category = models.CharField(max_length=50, choices=OPTION)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='Admin')
    image = models.ImageField(upload_to='blog/%Y/%m/')
    description = RichTextUploadingField()
    tag = models.ManyToManyField('Tag')
    slug = models.SlugField(unique=True)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-timestamp']
        verbose_name_plural = 'News or Article'

    # def get_absolute_url(self):
    #     return reverse('blog:articles-details',kwargs={'slug':self.slug})


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-timestamp']

emw/news_blog/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.core.paginator import Paginator
from .models import BlogNews

# Create your views here.


def news_blog_detail(request, slug):
    template_name = 'news_blog/news_blog_detail.html'
    bn = BlogNews.objects.all()
    news = bn.filter(category='news').count()
    articles = bn.filter(category='articles').count()
    qs = get_object_or_404(BlogNews, slug=slug)
    return render(request, template_name, {'obj': qs, 'news': news, 'articles': articles})


def new_articles(request, type):
    template_name = 'news_blog/news_blog.html'
    qs_all = BlogNews.objects.all()
    if type != 'all':
        news_articles_list = qs_all.filter(category=type)
        paginator = Paginator(news_articles_list, 3)
        page = request.GET.get('page')
        qs = paginator.get_page(page)
        return render(request, template_name, {'obj': qs, 'type': type})
    paginator = Paginator(qs_all, 3)
    page = request.GET.get('page')
    qs = paginator.get_page(page)
    return render(request, template_name, {'obj': qs, 'type': 'NEWS & ARTICLES'})


def search_blog_news(request):
    template_name = 'news_blog/search.html'
    if request.method == 'GET':
        query = request.GET.get('q')
        if query is not None:
            lookups = Q(title__icontains=query) | Q(
                description__icontains=query) | Q(category__icontains=query)
            results_list = BlogNews.objects.filter(lookups).distinct()
            paginator = Paginator(results_list, 3)
            page = request.GET.get('page')
            results = paginator.get_page(page)
            context = {'obj': results, 'query': query}
            return render(request, template_name, context)
        else:
            return render(request, template_name)
    else:
        return render(request, template_name)

emw/templates/base/snippets/news_blog.html
{% load static %}
<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
    <div class="post-block">
        <div class="post-content">
            <h4><a href="{% url 'news_blog:news_blog_detail' instance.slug %}">{{instance.title|title}}</a></h4>
            <p class="meta">
                <span class="meta-date">On {{instance.timestamp|date:"M d Y"}}</span>
            </p>
            <p>
                <span>
                    {{instance.description|truncatechars:100|safe}}
                </span>
            </p>

            <a href="{% url 'news_blog:news_blog_detail' instance.slug %}" class="btn btn-primary ">Read More</a>
        </div>
    </div>
</div>
<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
    <div class="post-img">
        <!-- post img -->
        <a href="{% url 'news_blog:news_blog_detail' instance.slug %}" class="imghover"><img
                src="{{instance.image.url}}" alt="{{instance.title|title}}" class="img-responsive"
                style="width: 750px; height: 380px;"></a>
    </div>
</div>

emw/templates/base/snippets/projects_snippets.html
{% load static %}
<!-- Card -->
<div class=" col-lg-4 col-md-4 col-sm-3 col-xs-12">
    <div class="card">
        <img class="card-img-top" src="{{instance.project_cover_image.url}}" alt="{{instance.company|title}}"
            class="img-responsive" style="height: 200px;">
        <div class="card-body post-block">
            <h4 class="card-title">{{instance.company|title}}</h4>
            <p class="card-text">{{instance.project_name|truncatechars:10}}</p>
            <a href="{% url 'portifolio_clients:project_details' instance.slug %}" class="btn btn-primary">Read More</a>
        </div>
    </div>

</div>
<!-- Card -->