emw/corporate/urls.py
from django.urls import path
from .views import (
    home,
    contact,
    contracting,
    logistics,
    construction_and_civils,
    joinery,
    steel_fabrication,
    general_trucks,
    specialised_trucks,
)

app_name = 'corporate'
urlpatterns = [
    path('', home, name='home'),
    path('contact-us', contact, name='contact'),
    path('contracting', contracting, name='contracting'),
    path('logistics', logistics, name='logistics'),
    path('contracting/construction-and-civils',
         construction_and_civils, name='construction_and_civils'),
    path('contracting/joinery', joinery, name='joinery'),
    path('contracting/steel-fabrication',
         steel_fabrication, name='steel_fabrication'),
    path('logistics/general-trucks', general_trucks, name='general_trucks'),
    path('logistics/specialised-trucks',
         specialised_trucks, name='specialised_trucks'),

]

emw/emw/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# default: "Django Administration"
admin.site.site_header = 'EMW Admin'
# default: "Site administration"
# admin.site.index_title = 'Features area'
# default: "Django site admin"
# admin.site.site_title = 'HTML title from adminsitration'

urlpatterns = [
    path('emw/admin/', admin.site.urls),
    path('', include('corporate.urls')),
    path('faqs/', include('faqs.urls')),
    path('', include('news_blog.urls')),
    path('', include('portifolio_clients.urls')),
    path('queries/', include('queries.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

emw/faqs/urls.py
from django.urls import path
from .views import faqs


app_name = 'faqs'
urlpatterns = [
    path('help/faqs', faqs, name="faqs"),

]

emw/news_blog/urls.py
from django.urls import path
from .views import (
    news_blog_detail,
    search_blog_news,
    new_articles
)


app_name = 'news_blog'
urlpatterns = [
    path('media/<slug:slug>', news_blog_detail, name='news_blog_detail'),
    path('<str:type>', new_articles, name='new_articles'),
    path('search', search_blog_news, name='search_blog_news'),

]

emw/portifolio_clients/urls.py
from django.urls import path
from .views import (
    project_details,
    projects
)


app_name = 'portifolio_clients'
urlpatterns = [
    path('project/<slug:slug>', project_details, name='project_details'),
    path('projects/all', projects, name='projects')

]

emw/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="keywords" content="">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Style CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.theme.default.css' %}" rel="stylesheet">
    <!-- FontAwesome CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/fontello.css' %}">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block css %}

    {% endblock %}
</head>

<body>
    <div class="header-wrapper navbar-fixed-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                    <a href="{% url 'corporate:home' %}"><img src="{% static 'images/logo/logo.png' %}" alt="logo"
                            style="border: 2px solid #FFDB59; width: auto;height: 50px;"></a>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <div class="navigation">
                        <div id="navigation">
                            <ul>
                                <li class="active"><a href="{% url 'corporate:home' %}" title="Home">Home</a></li>
                                <li class=""><a href="{% url 'portifolio_clients:projects' %}"
                                        title="About Us">Projects</a>
                                </li>
                                <li class=""><a href="{% url 'corporate:contact' %}" title="About Us">Contact Us</a>
                                </li>
                                <li class="has-sub"><a href="{% url 'corporate:home' %}" title="Services">Services</a>
                                    <ul>
                                        <li><a href="{% url 'corporate:logistics' %}" title="Logistics">Logistics</a>
                                        </li>
                                        <li><a href="{% url 'corporate:contracting' %}"
                                                title="Contracting">Contracting</a>
                                        </li>
                                    </ul>
                                </li>


                                <li class="has-sub"><a href="#" title="Blog ">Media</a>
                                    <ul>
                                        <li><a href="{% url 'news_blog:new_articles' 'news' %}" title="Blog">News</a>
                                        </li>
                                        <li><a href="{% url 'news_blog:new_articles' 'articles' %}"
                                                title="Blog Single ">Articles</a>
                                        </li>
                                    </ul>
                                </li>

                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-2 hidden-sm hidden-xs">
                    <div class="header-btn"><a href="{% url 'corporate:contact' %}" class="btn btn-primary btn-sm">Quick
                            Inquiry</a></div>
                </div>
            </div>
        </div>
    </div>
    <!-- header-section close -->
    {% block content %}

    {% endblock %}
    <!-- footer start -->
    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="ft-navigation">
                        <ul>
                            <li class="active"><a href="#" title="Home">Home</a></li>
                            <li><a href="{% url 'portifolio_clients:projects' %}" title="Projects">Projects</a> </li>
                            <li><a href="{% url 'corporate:contact' %}" title="Contact Us">Contact Us</a>
                            <li><a href="{% url 'faqs:faqs' %}" title="Contact Us">FAQs</a>
                            <li><a href="{% url 'news_blog:new_articles' 'news' %}" title="News">News</a></li>
                            <li><a href="{% url 'news_blog:new_articles' 'articles' %}" title="Articles">Articles</a>
                            </li>
                            <li><a href="{% url 'corporate:contracting' %}" title="Contracting ">Contracting</a>
                            <li><a href="{% url 'corporate:logistics' %}" title="Logistics ">Logistics</a>
                            </li>

                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="footer-widget">
                        <div class="footer-social">
                            <a href="#"><span><i class="fa fa-facebook-square"></i></span></a>

                            <a href="#"><span class="active"><i class="fa fa-twitter-square"></i> </span></a>
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                        <div class="footer-widget">
                            <ul>
                                <li>1 Adylinn Rd, Marlborough, Harare, Zimbabwe</li>
                                <li>+263 779 127 377 / +263 772 704 741
                                </li>
                                <li>admin@emw.co.zw</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center mt20">
                        © 2020 - {% now "Y" %} EMW Investments P/L. All Rights Reserved. Designed by <a
                            href="http://www.poppykode.com" style="color: #FFDB59;">poppykode</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- footer close -->
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/navigation.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/menumaker.js' %}" type="text/javascript"></script>
        <script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/slider.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.isotope.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/filter-script.js' %}"></script>
        {% block js %}

        {% endblock %}
</body>

</html>